apiVersion: v2
name: payload-processing
description: A Helm chart for the payload processing

type: application

version: 0.1.0

appVersion: "0.2.0"

dependencies:
  - name: payload-processor
    repository: oci://ghcr.io/llm-d/charts
    version: v0.1.0-rc.1
    alias: upstreamIpp
